### ISSUE TITLE
GPU instancing

### ISSUE THREAD

**Issue by bahadir147** [ColinLeung-NiloCat/UnityURPToonLitShaderExample#6]
Hello,

Thank you for shader, it is very good work.
But i need performance. How can add GPU instancing in shader?

**Comment by ColinLeung-NiloCat** [comment]
you can extract the outline pass to a RendererFeature, then all characters can batch into 1 SRP batch.
It is very easy to do, but I didn't do it because I don't want to increase the complexity (it is a tutorial shader)

**Comment by ColinLeung-NiloCat** [comment]
I wrote some notes about how to make this shader batching friendly here
https://github.com/ColinLeung-NiloCat/UnityURPToonLitShaderExample/blob/f557affc31551feb491b72598e73e115af9f126f/SimpleURPToonLitOutlineExample.shader#L185

if you encounter a CPU performance issue because of this shader, please open a new issue, thanks!
